image: docker
stages:
    - build
    - test
services:
    - docker:dind

build:
    stage: build
    script:
        - apk add --no-cache py-pip
        - pip install docker-compose
        - docker-compose -f Docker/docker-compose.yml up -d
        - docker exec php composer install
test:
    stage: test
    script:
        - docker exec php php bin/phpunit
