image: docker
services:
    - docker:dind
build:
    script:
        - apk add --no-cache py-pip
        - pip install docker-compose
        - docker-compose -f Docker/docker-compose.yml up -d
        - docker exec php composer install
        - docker exec php php bin/phpunit -c /var/www/imageUploader/phpunit.xml.dist --coverage-text
