version: "2.0"
services:
  image_uploader_nginx:
    image: nginx:latest
    volumes:
      - ../Code/PHP:/var/www/imageUploader
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - image_uploader_php
    ports:
      - 8080:80

  image_uploader_php:
      build:
        context: .
        dockerfile: Dockerfile_php
      environment:
          PHP_IDE_CONFIG: "serverName=jeophpardy.local"
      volumes:
          - ../Code/PHP:/var/www/imageUploader

  image_uploader_mysql:
      image: mysql:latest
      environment:
        MYSQL_ROOT_PASSWORD: toor
        MYSQL_USER: imageUploader
        MYSQL_PASSWORD: imageUploader
        MYSQL_DATABASE: imageUploader
      ports:
      - "3308:3306"
      restart: always
      volumes:
      - ../MysqlData:/var/lib/mysql

