version: "2.0"
services:
  image_uploader_nginx:
    image: nginx:latest
    volumes:
      - ../Code/PHP:/var/www/imageUploader
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - image_uploader_php

  image_uploader_php:
      build:
        context: .
        dockerfile: Dockerfile_php
      environment:
          PHP_IDE_CONFIG: "serverName=jeophpardy.local"
      volumes:
          - ../Code/PHP:/var/www/imageUploader

  image_uploader_postgres:
      image: postgres
      environment:
        POSTGRES_USER: Imaginer
        POSTGRES_PASSWORD: imageUploader
        POSTGRES_DB: imageUploader
      volumes:
        - ../postgres-data:/var/lib/postgresql/data
      ports:
        - 5432:5432

  adminer:
     image: adminer 
     restart: always
     ports:
      - 8080:8080
