FROM php:7.3.1-fpm as base

    RUN apt-get update
    RUN DEBIAN_FRONTEND=noninteractive apt-get -y --no-install-recommends install -y apt-utils \
        git \
        unzip \
        libpng-dev \
        wget \
        libjpeg62-turbo-dev \
        libfreetype6-dev \
        libzip-dev \
        libsodium-dev \
        mysql-client \
        vim

    RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    RUN echo "Europe/Berlin" > /etc/timezone
    RUN dpkg-reconfigure -f noninteractive tzdata
    RUN docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include
    RUN docker-php-ext-install pdo pcntl opcache gd zip calendar sodium pdo_mysql session

FROM base as xdebug

    ARG XDEBUGINI_PATH=/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    RUN pecl install xdebug-beta ; \
        docker-php-ext-enable xdebug; \
        echo "error_reporting = E_ALL" >> ${XDEBUGINI_PATH} ; \
        echo "display_startup_errors = On" >> ${XDEBUGINI_PATH} ; \
        echo "display_errors = On" >> ${XDEBUGINI_PATH} ; \
        echo "xdebug.remote_enable=on" >> ${XDEBUGINI_PATH} ; \
        echo "xdebug.remote_autostart=on" >> ${XDEBUGINI_PATH} ; \
        echo "xdebug.idekey=\"PHPSTORM\"" >> ${XDEBUGINI_PATH} ; \
        echo "xdebug.remote_port=9001" >> ${XDEBUGINI_PATH} ;

    RUN apt-get clean
    RUN rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
    RUN usermod -u 1000 www-data
    RUN groupmod -g 1000 www-data
    USER www-data:www-data
    WORKDIR /var/www/imageUploader

FROM base as prod

    RUN apt-get clean
    RUN rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
    RUN usermod -u 1000 www-data
    RUN groupmod -g 1000 www-data
    USER www-data:www-data
    WORKDIR /var/www/imageUploader