version: "2.0"
services:
  image_uploader_nginx:
    image: nginx:latest
    volumes:
      - ../Code/PHP:/var/www/imageUploader
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - image_uploader_php
    ports:
      - 8080:80

  image_uploader_php:
      build:
        context: .
        dockerfile: Dockerfile_php
      environment:
          PHP_IDE_CONFIG: "serverName=jeophpardy.local"
      volumes:
          - ../Code/PHP:/var/www/imageUploader

  image_uploader_postgres:
      image: postgres
      environment:
        POSTGRES_PASSWORD: imageUploader
      restart: always
      volumes:
        - ./postgres-data:/var/lib/postgresql/data

