version: "2.0"
services:
  image_uploader_nginx:
    image: nginx:latest
    volumes:
      - ../Code/PHP:/var/www/imageUploader
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www/imageUploader
    ports:
      - 80:80
    links:
      - image_uploader_php

  image_uploader_php:
    build:
      context: .
      dockerfile: Dockerfile_php
    env_file:
      - mysql_env
    volumes:
      - ../Code/PHP:/var/www/imageUploader
    working_dir: /var/www/imageUploader

  image_uploader_db:
    image: mysql:5.7.25
    container_name: ImageUploaderDb
    env_file:
      - mysql_env
    ports:
      - 3306:3306
    volumes:
      - ../mysql-data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
